import 'package:flutter/foundation.dart';

/// Request payload for pre-registering / verifying a batch with Express AI.
/// Matches [VerifyRegistrationRequest] from React [api.ts].
@immutable
class VerifyRegistrationRequest {
  /// Name of the product (e.g., Arabica Coffee).
  final String productName;

  /// Unique harvest batch code (e.g., BATCH-2026-001).
  final String harvestBatch;

  /// Quantity string or numeric value.
  final String quantity;

  /// Unit of measurement (e.g., kg).
  final String unit;

  /// Location string.
  final String location;

  /// Harvest date formatted as YYYY-MM-DD.
  final String harvestDate;

  /// Optional metadata string or JSON.
  final String? metadata;

  /// Creates an immutable [VerifyRegistrationRequest].
  const VerifyRegistrationRequest({
    required this.productName,
    required this.harvestBatch,
    required this.quantity,
    required this.unit,
    required this.location,
    required this.harvestDate,
    this.metadata,
  });

  /// Serializes to a JSON map.
  Map<String, dynamic> toJson() => {
    'productName': productName,
    'harvestBatch': harvestBatch,
    'quantity': quantity,
    'unit': unit,
    'location': location,
    'harvestDate': harvestDate,
    if (metadata != null) 'metadata': metadata,
  };
}

/// Cooperative readiness score and notes from verification.
@immutable
class CooperativeReadiness {
  /// Readiness status string ("Ready" or "Review Required").
  final String status;

  /// Explanatory notes.
  final List<String> notes;

  /// Creates an immutable [CooperativeReadiness].
  const CooperativeReadiness({required this.status, required this.notes});

  /// Deserializes from a JSON map.
  factory CooperativeReadiness.fromJson(Map<String, dynamic> json) {
    return CooperativeReadiness(
      status: json['status'] as String? ?? 'Ready',
      notes:
          (json['notes'] as List?)?.map((e) => e.toString()).toList() ??
          const [],
    );
  }

  /// Serializes to a JSON map.
  Map<String, dynamic> toJson() => {'status': status, 'notes': notes};
}

/// Detailed verification summary returned by AI or local fallback.
/// Matches data inside [VerifyRegistrationResponse] from React [api.ts].
@immutable
class VerifyRegistrationSummary {
  /// One-sentence summary of product provenance.
  final String productSummary;

  /// Normalized summary of submitted batch parameters.
  final Map<String, String> verificationSummary;

  /// Warning messages flagged during analysis.
  final List<String> warnings;

  /// Consistency checks performed on harvest data.
  final List<String> consistencyChecks;

  /// Cooperative export readiness status.
  final CooperativeReadiness cooperativeReadiness;

  /// Numerical or text statistics summary.
  final Map<String, String> statistics;

  /// Whether this summary was generated by the client fallback.
  final bool fallback;

  /// Optional fallback warning message.
  final String? warningMessage;

  /// Duration of verification in milliseconds.
  final int? ms;

  /// Optional error string if partial failure occurred.
  final String? error;

  /// Creates an immutable [VerifyRegistrationSummary].
  const VerifyRegistrationSummary({
    required this.productSummary,
    required this.verificationSummary,
    required this.warnings,
    required this.consistencyChecks,
    required this.cooperativeReadiness,
    required this.statistics,
    this.fallback = false,
    this.warningMessage,
    this.ms,
    this.error,
  });

  /// Deserializes from a JSON map.
  factory VerifyRegistrationSummary.fromJson(Map<String, dynamic> json) {
    return VerifyRegistrationSummary(
      productSummary: json['productSummary'] as String? ?? '',
      verificationSummary:
          (json['verificationSummary'] as Map?)?.map(
            (k, v) => MapEntry(k.toString(), v.toString()),
          ) ??
          const {},
      warnings:
          (json['warnings'] as List?)?.map((e) => e.toString()).toList() ??
          const [],
      consistencyChecks:
          (json['consistencyChecks'] as List?)
              ?.map((e) => e.toString())
              .toList() ??
          const [],
      cooperativeReadiness:
          json['cooperativeReadiness'] != null &&
              json['cooperativeReadiness'] is Map
          ? CooperativeReadiness.fromJson(
              Map<String, dynamic>.from(json['cooperativeReadiness'] as Map),
            )
          : const CooperativeReadiness(status: 'Ready', notes: []),
      statistics:
          (json['statistics'] as Map?)?.map(
            (k, v) => MapEntry(k.toString(), v.toString()),
          ) ??
          const {},
      fallback: json['fallback'] == true,
      warningMessage: json['warningMessage'] as String?,
      ms: (json['ms'] as num?)?.toInt(),
      error: json['error'] as String?,
    );
  }

  /// Serializes to a JSON map.
  Map<String, dynamic> toJson() => {
    'productSummary': productSummary,
    'verificationSummary': verificationSummary,
    'warnings': warnings,
    'consistencyChecks': consistencyChecks,
    'cooperativeReadiness': cooperativeReadiness.toJson(),
    'statistics': statistics,
    'fallback': fallback,
    if (warningMessage != null) 'warningMessage': warningMessage,
    if (ms != null) 'ms': ms,
    if (error != null) 'error': error,
  };
}

/// Response container for registration AI verification.
@immutable
class VerifyRegistrationResponse {
  /// Whether verification request succeeded.
  final bool ok;

  /// The resulting verification summary data.
  final VerifyRegistrationSummary data;

  /// Creates an immutable [VerifyRegistrationResponse].
  const VerifyRegistrationResponse({required this.ok, required this.data});

  /// Deserializes from a JSON map.
  factory VerifyRegistrationResponse.fromJson(Map<String, dynamic> json) {
    return VerifyRegistrationResponse(
      ok: json['ok'] == true,
      data: VerifyRegistrationSummary.fromJson(
        Map<String, dynamic>.from(json['data'] as Map? ?? {}),
      ),
    );
  }

  /// Serializes to a JSON map.
  Map<String, dynamic> toJson() => {'ok': ok, 'data': data.toJson()};
}

/// Generates a local fallback verification summary matching React's
/// [generateLocalFallbackVerification] in [api.ts] exactly.
VerifyRegistrationSummary generateLocalFallbackVerification(
  VerifyRegistrationRequest data,
) {
  final cleanQty = data.quantity.trim();
  final qtyStr = cleanQty.isNotEmpty ? '$cleanQty ${data.unit}' : '';
  final productSummary = data.productName.isNotEmpty
      ? 'Local verification for ${data.productName} (${data.harvestBatch.isNotEmpty ? data.harvestBatch : "No batch specified"}).'
      : 'Local verification summary.';

  final warnings = <String>[];
  final consistencyChecks = <String>[];
  final notes = <String>[];

  if (data.location.trim().length < 3) {
    warnings.add('Harvest location missing or too vague');
    notes.add('Location verification failed');
  } else {
    notes.add('Location provided');
  }

  if (data.harvestDate.isEmpty) {
    warnings.add('Harvest date not specified');
    notes.add('Harvest date missing');
  } else {
    try {
      final todayISO = DateTime.now().toIso8601String().split('T')[0];
      if (data.harvestDate.compareTo(todayISO) > 0) {
        consistencyChecks.add('Future harvest date detected');
        notes.add('Harvest date is in the future');
      } else {
        notes.add('Harvest date verified');
      }
    } catch (_) {
      notes.add('Harvest date checked');
    }
  }

  final status = warnings.isNotEmpty || consistencyChecks.isNotEmpty
      ? 'Review Required'
      : 'Ready';

  return VerifyRegistrationSummary(
    productSummary: productSummary,
    verificationSummary: {
      'quantity': cleanQty.isNotEmpty
          ? 'Provided: $qtyStr'
          : 'Quantity not specified',
      'harvestBatch': data.harvestBatch.isNotEmpty
          ? 'Provided: ${data.harvestBatch}'
          : 'Harvest batch not specified',
      'location': data.location.isNotEmpty
          ? 'Provided: ${data.location}'
          : 'Location not specified',
      'harvestDate': data.harvestDate.isNotEmpty
          ? 'Provided: ${data.harvestDate}'
          : 'Harvest date not specified',
    },
    warnings: warnings,
    consistencyChecks: consistencyChecks,
    cooperativeReadiness: CooperativeReadiness(status: status, notes: notes),
    statistics: {
      'batchNumber': data.harvestBatch.isNotEmpty ? data.harvestBatch : 'N/A',
      'quantity': qtyStr.isNotEmpty ? qtyStr : 'N/A',
      'location': data.location.isNotEmpty ? data.location : 'N/A',
      'harvestDate': data.harvestDate.isNotEmpty ? data.harvestDate : 'N/A',
    },
    fallback: true,
    warningMessage: 'AI verification unavailable. Manual review recommended.',
  );
}
